# Generated by Django 6.1 on 2026-08-16 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('expense_submitted', 'Expense Submitted'), ('expense_approved', 'Expense Approved'), ('expense_rejected', 'Expense Rejected'), ('ocr_completed', 'OCR Completed'), ('ocr_failed', 'OCR Failed'), ('reimbursement_created', 'Reimbursement Created'), ('reimbursement_processing', 'Reimbursement Processing'), ('reimbursement_paid', 'Reimbursement Paid'), ('reimbursement_failed', 'Reimbursement Failed'), ('budget_warning', 'Budget Warning'), ('system', 'System')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
